<?php
declare(strict_types=1);

namespace App\Controllers;

use App\Core\Auth;use App\Core\Database;use App\Core\View;use PDOException;use Throwable;

final class UserController
{
    public function index():void{Auth::requirePermission('*');$q=trim((string)($_GET['q']??''));$stmt=Database::connection()->prepare('SELECT u.*,r.nombre rol,p.nombre_completo FROM usuarios u JOIN roles r ON r.id_rol=u.id_rol LEFT JOIN perfiles_usuarios p ON p.id_usuario=u.id_usuario WHERE u.nombre_usuario LIKE ? OR u.correo LIKE ? OR p.nombre_completo LIKE ? ORDER BY u.fecha_registro DESC');$like="%{$q}%";$stmt->execute([$like,$like,$like]);$users=$stmt->fetchAll();View::render('users/index',compact('users','q'));}
    public function create():void{Auth::requirePermission('*');$roles=$this->roles();View::render('users/form',['account'=>null,'roles'=>$roles]);}
    public function store():void{Auth::requirePermission('*');require_csrf();$this->save();}
    public function edit(string $id):void{Auth::requirePermission('*');$account=$this->find((int)$id);if(!$account){http_response_code(404);View::render('errors/404');return;}$roles=$this->roles();View::render('users/form',compact('account','roles'));}
    public function update(string $id):void{Auth::requirePermission('*');require_csrf();$this->save((int)$id);}
    public function toggle(string $id):void{Auth::requirePermission('*');require_csrf();if((int)$id===(int)Auth::user()['id_usuario']){flash('error','No puedes desactivar tu propia cuenta.');redirect('/usuarios');}Database::connection()->prepare('UPDATE usuarios SET estado=1-estado,ultima_actualizacion=NOW() WHERE id_usuario=?')->execute([(int)$id]);flash('success','Estado de la cuenta actualizado.');redirect('/usuarios');}
    public function resetPassword(string $id):void{Auth::requirePermission('*');require_csrf();$password=(string)($_POST['nueva_contrasena']??'');if(strlen($password)<8){flash('error','La contraseña temporal debe tener al menos 8 caracteres.');redirect('/usuarios/'.$id.'/editar');}Database::connection()->prepare('UPDATE usuarios SET contrasena_hash=?,ultima_actualizacion=NOW() WHERE id_usuario=?')->execute([password_hash($password,PASSWORD_DEFAULT),(int)$id]);flash('success','Contraseña restablecida correctamente.');redirect('/usuarios/'.$id.'/editar');}
    private function save(?int $id=null):void{$username=trim((string)($_POST['nombre_usuario']??''));$email=mb_strtolower(trim((string)($_POST['correo']??'')));$name=trim((string)($_POST['nombre_completo']??''));$role=(int)($_POST['id_rol']??0);$password=(string)($_POST['contrasena']??'');if($username===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$name===''||!$role||(!$id&&strlen($password)<8)){flash('error','Completa los campos correctamente; la contraseña inicial requiere 8 caracteres.');remember_input($_POST);redirect($id?"/usuarios/{$id}/editar":'/usuarios/crear');}$db=Database::connection();try{$db->beginTransaction();if($id){$db->prepare('UPDATE usuarios SET id_rol=?,nombre_usuario=?,correo=?,ultima_actualizacion=NOW() WHERE id_usuario=?')->execute([$role,$username,$email,$id]);$db->prepare('UPDATE perfiles_usuarios SET nombre_completo=?,telefono=?,fecha_actualizacion=NOW() WHERE id_usuario=?')->execute([$name,trim((string)($_POST['telefono']??''))?:null,$id]);}else{$db->prepare('INSERT INTO usuarios(id_rol,nombre_usuario,correo,contrasena_hash) VALUES(?,?,?,?)')->execute([$role,$username,$email,password_hash($password,PASSWORD_DEFAULT)]);$new=(int)$db->lastInsertId();$db->prepare('INSERT INTO perfiles_usuarios(id_usuario,nombre_completo,telefono) VALUES(?,?,?)')->execute([$new,$name,trim((string)($_POST['telefono']??''))?:null]);}$db->commit();clear_old();flash('success','Usuario guardado correctamente.');redirect('/usuarios');}catch(PDOException $e){if($db->inTransaction())$db->rollBack();if($e->getCode()==='23000'){flash('error','El usuario o correo ya está registrado.');remember_input($_POST);redirect($id?"/usuarios/{$id}/editar":'/usuarios/crear');}throw $e;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
    private function roles():array{$rows=Database::connection()->query('SELECT id_rol,nombre FROM roles WHERE estado=1 ORDER BY nombre')->fetchAll();foreach($rows as &$row)$row['id_rol']=(int)$row['id_rol'];return $rows;}
    private function find(int $id):?array{$s=Database::connection()->prepare('SELECT u.*,p.nombre_completo,p.telefono FROM usuarios u LEFT JOIN perfiles_usuarios p ON p.id_usuario=u.id_usuario WHERE u.id_usuario=?');$s->execute([$id]);return $s->fetch()?:null;}
}
